apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tfapply
spec:
  workspaces:
    - name: src
      description: ""
    - name: secrets
      mountPath: /root/.aws
  params:
    - name: terraformDir
      description: terraform source code directory where lint tools run
      default: .
    - name: tfvars
      description: path to tfvars file
      default: terraform.tfvars
    - name: tfplan
      description: path to tfplan file
      default: ""
    - name: awsProfile
      description: aws credential profile name
      default: "default"
  results:
    - name: tfplanPath
      description: "path to tfplan file"
  steps:
    - name: tfapply
      image: docker.io/mkikyotani/tf-tools:0.0.1
      script: |
        export AWS_PROFILE=$(params.awsProfile)
        terraform init
        terraform apply -auto-approve -var-file $(params.tfvars) "$(params.tfplan)"
      workingDir: "/workspace/src/$(params.terraformDir)"





