apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: tfplan
spec:
  workspaces:
    - name: src
      description: ""
    - name: secrets
      mountPath: /tekton/home/.aws
  params:
    - name: terraformDir
      description: terraform source code directory where lint tools run
      default: .
    - name: tfvars
      description: path to tfvars file
      default: terraform.tfvars
  results:
    - name: tfplanPath
      description: "path to tfplan file"
  steps:
    - name: tfplan
      image: docker.io/mkikyotani/tf-tools:0.0.1
      script: |
        tfplanPath="/workspace/src/$(params.terraformDir)/$(context.taskRun.uid).tfplan"
        terraform init
        terraform plan -var-file $(params.tfvars) -out "${tfplanPath}"
        echo $tfplanPath | tee $(results.tfplanPath.path)
      workingDir: "/workspace/src/$(params.terraformDir)"





