---
kind: "Pipeline"
apiVersion: "tekton.dev/v1beta1"
metadata:
  name: "app-deploy"
  namespace: "app"
spec:
  workspaces:
  - name: "src"
  - name: dockerconfig
  params:
  - name: "repoUrl"
    type: "string"
  - name: appName
    type: "string"
  - name: imageOrg
    type: string
    default: mkikyotani
  - name: imageTag
    type: string
    default: 0.0.1
  tasks:
  - name: "fetch-source"
    taskRef:
      kind: "Task"
      name: "git-clone"
    workspaces:
    - name: "output"
      workspace: "src"
    params:
    - name: "url"
      value: "$(params.repoUrl)"