---
kind: "Pipeline"
apiVersion: "tekton.dev/v1beta1"
metadata:
  name: "app"
  namespace: "app"
spec:
  workspaces:
  - name: "src"
  - name: dockerconfig
  params:
  - name: "repo_url"
    type: "string"
  tasks:
  - name: "fetch-source"
    params:
    - name: "url"
      value: "$(params.repo_url)"
    taskRef:
      kind: "Task"
      name: "git-clone"
    workspaces:
    - name: "output"
      workspace: "src"
  - name: build-and-push
    taskRef:
      kind: Task
      name: kaniko
    workspaces:
    - name: "source"
      workspace: "src"
    - name: dockerconfig
      workspace: dockerconfig
    params:
      - name: IMAGE
        value: "docker.io/mkikyotani/devsecops-demo-app"
      - name: CONTEXT
        value: ./app
    runAfter:
      - fetch-source