---
kind: "Pipeline"
apiVersion: "tekton.dev/v1beta1"
metadata:
  creationTimestamp: "2022-02-22T06:17:06Z"
  name: "pr-infra"
  namespace: "app"
  resourceVersion: "371535"
  uid: "5286d231-015a-4bd2-8a19-59ef05c5d197"
spec:
  params:
  - name: "repo_url"
    type: "string"
  tasks:
  - name: "fetch-source"
    params:
    - name: "url"
      value: "$(params.repo_url)"
    taskRef:
      kind: "Task"
      name: "git-clone"
    workspaces:
    - name: "output"
      workspace: "src"
  - name: "lint"
    params:
    - name: "terraformDir"
      value: "terraform"
    runAfter:
    - "fetch-source"
    taskRef:
      kind: "Task"
      name: "tflint"
    workspaces:
    - name: "src"
      workspace: "src"
    - name: "secrets"
      workspace: "secrets"
  - name: "tfplan"
    params:
    - name: "terraformDir"
      value: "terraform"
    runAfter:
    - "lint"
    taskRef:
      kind: "Task"
      name: "tfplan"
    workspaces:
    - name: "src"
      workspace: "src"
    - name: "secrets"
      workspace: "secrets"
  - name: "tfapply"
    params:
    - name: "terraformDir"
      value: "terraform"
    - name: "tfplan"
      value: "$(tasks.tfplan.results.tfplanPath)"
    runAfter:
    - "tfplan"
    taskRef:
      kind: "Task"
      name: "tfapply"
    workspaces:
    - name: "src"
      workspace: "src"
    - name: "secrets"
      workspace: "secrets"
  workspaces:
  - name: "src"
  - name: "secrets"
