---
kind: "Pipeline"
apiVersion: "tekton.dev/v1beta1"
metadata:
  name: "pr-infra"
  namespace: "app"
spec:
  workspaces:
    - name: "src"
    - name: "secrets"
  params:
    - name: "repo_url"
      type: "string"
  tasks:
    - name: "fetch-source"
      params:
        - name: "url"
          value: "$(params.repo_url)"
      taskRef:
        kind: "Task"
        name: "git-clone"
      workspaces:
        - name: "output"
          workspace: "src"
    - name: "lint"
      params:
        - name: "terraformDir"
          value: "terraform"
      runAfter:
        - "fetch-source"
      taskRef:
        kind: "Task"
        name: "tflint"
      workspaces:
        - name: "src"
          workspace: "src"
        - name: "secrets"
          workspace: "secrets"
    - name: "tfplan"
      taskRef:
        kind: Task
        name: tfplan
      workspaces:
        - name: "src"
          workspace: "src"
        - name: "secrets"
          workspace: "secrets"
      params:
        - name: "terraformDir"
          value: "terraform"
      runAfter:
        - "lint"
    - name: "tfapply"
      taskRef:
        kind: Task
        name: tfapply
      workspaces:
        - name: "src"
          workspace: "src"
        - name: "secrets"
          workspace: "secrets"
      params:
        - name: "terraformDir"
          value: "terraform"
        - name: "tfplan"
          value: "$(tasks.tfplan.results.tfplanPath)"
      runAfter:
        - tfplan
