apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: app-build-run-
  namespace: app
spec:
  pipelineRef:
    name: app-build
  params:
    - name: repoUrl
      value: https://github.com/kikyomits/devsecops-demo.git
    - name: appName
      value: devsecops-demo-app
    - name: imageOrg
      value: mkikyotani
    - name: imageTag
      value: 0.0.1
  workspaces:
    - name: src
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    - name: dockerconfig
      secret:
        secretName: docker-secret
    - name: sonar-settings
      configMap:
        name: "sonar-properties"