apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: go-build-run-
  namespace: app
spec:
  pipelineRef:
    name: go-build-demo
  params:
    - name: repoUrl
      value: https://github.com/kikyomits/devsecops-demo.git
    - name: appName
      value: devsecops-demo-app
    - name: imageOrg
      value: mkikyotani
    - name: imageTag
      value: 0.0.1
  workspaces:
    - name: src
      persistentVolumeClaim:
        claimName: pvc-tekton
    - name: dockerconfig
      secret:
        secretName: docker-secret
    - name: sonar-settings
      configMap:
        name: "sonar-properties"