apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: app-run-
  namespace: app
spec:
  pipelineRef:
    name: app
  params:
    - name: repo_url
      value: https://github.com/kikyomits/devsecops-demo.git
  workspaces:
    - name: src
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 100Mi
    - name: dockerconfig
      secret:
        secretName: docker-secret